### ISSUE TITLE
[REFACTOR] MyPage

### ISSUE THREAD

**Issue by SeungEEE** [UMC-with-you/WithYouApp#33]
## Description
- BaseUIView / BaseViewController 활용한 refactoring

## To-Do
- [ ] MyPageViewController
- [ ] ProfileEditViewController

**Comment by dogyungkim** [comment]
ViewController가 Override하는 BaseViewController의 메서드(setup, setUI 등등)는 이미 BaseViewController의 viewDidLoad()에서 호출이 되기때문에 따로 viewDidLoad()에서 다신 선언 해줄 필요가 없음!
- ProfileEditView의 viewDidLoad()는 삭제해도 기능상 문제가 없고
- MyPage는 setViewProperty함수가 따로 선언 되어 있어서  viewDidLoad를 override해야함. 하지만 super.viewDidLoad()를 호출하면 setUp, setUI 같은건 다 호출이 되기 때문에 super.viewDidLoad()를 호출하고, 따로 생성한 메서드를 호출해주면 코드를 줄일 수 있음!

확인해보고 수정해서 다시 커밋 해봐~

**Comment by SeungEEE** [comment]
다시 커밋 했슴다요

2024년 5월 28일 (화) 오전 11:34, Do Gyung Kim (Bryan) ***@***.***>님이
작성:

**Comment by dogyungkim** [comment]
Good!!
